### PR TITLE
Update .npmrc

### PR DESCRIPTION
**Pull request by paulgschwendtner**

### CODE REVIEW

**Review by paulgschwendtner — COMMENTED** [review]
/approve-ssr-golden

**Review by paulgschwendtner — COMMENTED** [review]
/approve-ssr-golden

**Review by devversion — COMMENTED** [review]
/approve-ssr-golden

**Review by paulgschwendtner — COMMENTED** [review]
/approve-ssr-golden

**Review by devversion — COMMENTED** [review]
/approve-ssr-golden

**Review by devversion — COMMENTED** [review]
/approve-ssr-golden

**Review by devversion — COMMENTED** [review]
/approve-ssr-golden

**Review by paulgschwendtner — COMMENTED** [review]
/approve-ssr-golden

**Review by paulgschwendtner — COMMENTED** [review]
/approve-ssr-golden

**Pull request closed without merging**
